#!/bin/bash

# alias tpdg='. ~/nadim/devel/repositories/tpd/tpd'
# tpdg ; tpd | { echo -e "ab\nde" ; echo 1 ; } | sed -e 's/a/A/'

run_commands()
{
[[ -e collect ]] && pipeline=$(perl -pe 's/^.*tpd\s+\|?//' collect)
eval "$pipeline"
}

_capture_exec()
{
[ -n "$COMP_LINE" ] && return  # do nothing if completing

[ "shopt -u extdebug" == "$BASH_COMMAND" ] && return 0 # don't get locked

[[ -e collect ]] &&  
	{ <&5 read -t 0.05 t || { trap - DEBUG ; shopt -u extdebug ; rm -f to_collect ; run_commands ; } ; } || 
	{ [[ $BASH_COMMAND =~ ^tpd ]] && 
		{
		< <(history 1 | tee collect) IFS='|' read -ra cmds ; t=$((${#cmds[@]} - 1))
		mkfifo to_collect ; exec 5<>to_collect ; for s in $(seq $t) ; do echo $s >&5 ; done
		}
	}

return 1 # skip execution
}

rm -f collect to_collect

[[ "$0" != "$BASH_SOURCE" ]] && { shopt -s extdebug  ; trap '_capture_exec' DEBUG ; true ; } 


